http:
  routers:
    adminer:
      rule: "Host(`adminer.myproject.com`)"
      entryPoints:
        - websecure
      service: adminer_service
      middlewares:
        - redirect-to-https
        - auth
      tls:
        domains:
          - main: "adminer.myproject.com"

  middlewares:
    auth:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - Authorization
#    role-check:
#      plugin:
#        jwt:
#          jwksUri: "https://keycloak.myproject.com/realms/keycloak_platform/protocol/openid-connect/certs"
#          rules:
#            - claim: "realm_access.roles"
#              contains: "developer"