http:
  routers:
    back1:
      rule: "Host(`back1.myproject.com`)"
      entryPoints:
        - websecure
      service: back1_service
      middlewares:
        - redirect-to-https
      tls:
        domains:
          - main: "back1.myproject.com"
