http:
  routers:
    back1:
      rule: "Host(`back1.myproject.com`)"
      entryPoints:
        - websecure
      service: back1_service
      middlewares:
        - redirect-to-https
        - header-back1
        - auth_middleware
      tls:
        domains:
          - main: "back1.myproject.com"

  middlewares:
    header-back1:
      headers:
        customRequestHeaders:
          X-Project-Name: "back-1"