services:
  swagger-ui:
    container_name: swagger
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8081:8080
    volumes:
      - .:/openapi
    environment:
      - SWAGGER_JSON=/openapi/swagger.yml
    networks:
      - keycloak_network
    restart: unless-stopped