include:
  - ./.docker/swagger/docker-compose.yml
  - ./.docker/postgresql/docker-compose.yml
  - ./.docker/traefik/docker-compose.yml
  - ./.docker/python_middleware/docker-compose.yml
  - ./.docker/task_api/docker-compose.yml
  - ./.docker/webserver/docker-compose.yml
  - ./.docker/keycloak/docker-compose.yml

services:
  backend_1:
    image: arxi0xyz/python_simple
    container_name: back1
    environment:
      - APP_NAME=first application
    restart: unless-stopped
    networks:
      - keycloak_network

networks:
  keycloak_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgresql_data:
