services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_BOOT_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_BOOT_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/${KEYCLOAK_DATABASE}
      - KC_DB_USERNAME=${KEYCLOAK_DATABASE_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_DOMAIN}
    ports:
      - ${KEYCLOAK_PORT}:8080
    networks:
      - keycloak_network
    command: start-dev

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: .docker/laravel/Dockerfile
    volumes:
      - ./.docker/laravel/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./.docker/laravel/supervisor/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./.docker/laravel/supervisor/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
      - ./.docker/laravel/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./backend:/var/www:delegated
    networks:
      - keycloak_network
    healthcheck:
      test: ['CMD', 'php-fpm', '-t']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    user: www-data


  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - '80:80'
    environment:
      - KEYCLOAK_DOMAIN=${KEYCLOAK_DOMAIN}
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/templates:/etc/nginx/templates
      - ./.docker/nginx/logs:/var/log/nginx
      - ./backend:/var/www/backend
    networks:
      - keycloak_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/up']
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql: 
    container_name: db
    build: 
      context: .
      dockerfile: ./.docker/postgresql/Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/17/docker

      - KEYCLOAK_DATABASE=${KEYCLOAK_DATABASE}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
      - ./.docker/postgresql/scripts/keycloak_init_db.sh:/docker-entrypoint-initdb.d/keycloak_init_db.sh
    networks:
      - keycloak_network
  swagger-ui:
    container_name: swagger
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8081:8080
    volumes:
      - ./.docker/swagger:/openapi
    environment:
      - SWAGGER_JSON=/openapi/swagger.yml
    networks:
      - keycloak_network
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8082:8080
    networks:
      - keycloak_network

networks:
  keycloak_network:
    name: keycloak_network

volumes:
  postgresql_data:
    