include:
  - ./.docker/swagger/docker-compose.yml
  - ./.docker/postgresql/docker-compose.yml
  - ./.docker/traefik/docker-compose.yml
  - ./.docker/python_middleware/docker-compose.yml
  - ./.docker/task_api/docker-compose.yml
  - ./.docker/webserver/docker-compose.yml
  - ./.docker/keycloak/docker-compose.yml
  - ./.docker/redis/docker-compose.yml

networks:
  keycloak_network:
    ipam:
      driver: default
      