x-default-properties: &default-properties
  restart: unless-stopped
  networks:
    - keycloak_network

include:
  - ./.docker/swagger/docker-compose.yml
  - ./.docker/postgresql/docker-compose.yml
  - ./.docker/traefik/docker-compose.yml
  - ./.docker/python_middleware/docker-compose.yml
  - ./.docker/laravel_backend/docker-compose.yml
  - ./.docker/webserver/docker-compose.yml

services:
  keycloak:
    <<: *default-properties
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_BOOT_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_BOOT_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/${KEYCLOAK_DATABASE}
      - KC_DB_USERNAME=${KEYCLOAK_DATABASE_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_DOMAIN}
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_RELATIVE_PATH=/
      - DISABLE_SSL_VERIFY=true

    command: start-dev
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "curl --head -fsS http://localhost:9000/health/ready",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend_1:
    image: arxi0xyz/python_simple
    container_name: back1
    environment:
      - APP_NAME=first application
    <<: *default-properties

  backend_2:
    image: arxi0xyz/python_simple
    container_name: back2
    environment:
      - APP_NAME=second application
    <<: *default-properties

networks:
  keycloak_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgresql_data:
