services:
  postgresql:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/17/docker

      - KEYCLOAK_DATABASE=${KEYCLOAK_DATABASE}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
      - ./scripts/keycloak_init_db.sh:/docker-entrypoint-initdb.d/keycloak_init_db.sh
    networks:
      - keycloak_network
