services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis:/data
    networks:
      - keycloak_network
    restart: unless-stopped
    
volumes:
  redis: