entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls: true

providers:
  file:
    directory: /etc/traefik/dynamic/
    watch: true

log:
  level: TRACE
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: json
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: true

ping: {}

experimental:
  plugins:
    jwt-validation:
      moduleName: "github.com/agilezebra/jwt-middleware"
      version: "v1.3.2"