services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_BOOT_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_BOOT_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/${KEYCLOAK_DATABASE}
      - KC_DB_USERNAME=${KEYCLOAK_DATABASE_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - KC_HOSTNAME=${KEYCLOAK_DOMAIN}
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_RELATIVE_PATH=/
      - DISABLE_SSL_VERIFY=true
    command: start-dev
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "curl --head -fsS http://localhost:9000/health/ready",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - keycloak_network
